# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vanshitaportfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://regportfolio.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d98202f8e2a84ca0935669ada050bbc2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c6a2e6c466614f41a9f22c40f8adf4cc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: regportfolio.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d98202f8e2a84ca0935669ada050bbc2 }}/my-portfolio-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vanshitaportfolio'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2b20896bbff8428a9798eaa2ffd30a4c }}
        images: 'regportfolio.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d98202f8e2a84ca0935669ada050bbc2 }}/my-portfolio-image:${{ github.sha }}'